export { aiCoachService } from './core/ai-coach.engine.js';

export type {
  GoalCategory,
  ConversationPhase,
  SupportedLanguage,
  ChatMessage,
  ConversationContext,
  ExtractedInsight,
  AICoachResponse,
  AICoachSession,
  HealthImageType,
  ImageValidationResult,
  ImageAnalysisResult,
  UploadedHealthImage,
  AssessmentResponseInput,
  BodyStatsInput,
  GeneratedGoal,
  GenerateGoalsRequest,
  GenerateGoalsResponse,
  DietPlanRequest,
  GeneratedDietPlan,
  MCQCategory,
  MCQOption,
  MCQQuestion,
  MCQGenerationRequest,
  MCQGenerationResponse,
  BatchMCQRequest,
  BatchMCQResponse,
  LifeCoachQuestionsRequest,
  LifeCoachQuestionsResponse,
  LifeCoachQuestionItem,
} from './types/index.js';
